### ISSUE TITLE
Initial TODO list

### ISSUE THREAD

**Issue by dpc** [dpc/mioco#1]
* [x] Is this practical and does it make sense?
* [ ] Evaluate using `coroutine::Context` instead of `coroutine::Coroutine`. Maybe there are some gains by not using global scheduling etc.
* [x] Should more than just `TcpStream` be supported?
* [x] API to trim needless Stacks and Contexts allocations?

**Comment by dpc** [comment]
Closing this, moving remaining to #6.
