### ISSUE TITLE
0.1.0 TODO

### ISSUE THREAD

**Issue by dpc** [dpc/mioco#5]
* [x] Fix select operations
* [x] Update https://github.com/dpc/colerr
* [x] Squash and merge new-design into mainline
* [ ] Update benchmarks
 * [x] ~~Write automatic benchmarks script~~, too lazy for that
  * [ ] against raw-mio echo
  * [x] against libev
  * [x] against Node.js echo

**Comment by dpc** [comment]
See https://github.com/hjr3/mob/issues/1
